
import { Building, Resources, Research, Ship, Defense, Officer, Quest, User, Talent, Artifact } from './types';

export const INITIAL_RESOURCES: Resources = {
  risitasium: 500,
  stickers: 300,
  sel: 0,
  karma: 0,
  karmaMax: 0,
  redpills: 50,
};

export const RAPID_FIRE: { [attackerId: string]: { [targetId: string]: number } } = {
    'croiseur': { 'chasseur_leger': 6, 'sonde': 5, 'satellite_solaire': 5 },
    'destructeur': { 'croiseur': 2, 'laser_gneugneu': 5, 'satellite_solaire': 5 },
    'etoile_noire': { 'croiseur': 10, 'vaisseau_bataille': 5, 'destructeur': 2, 'satellite_solaire': 100 },
    'chasseur_lourd': { 'petit_transporteur': 3, 'satellite_solaire': 5 },
};

export const QUEST_DB: Quest[] = [
    {
        id: 'q_start',
        title: 'Première Pierre',
        description: 'Construire une Mine de Risitium niveau 1.',
        reward: { stickers: 200 },
        condition: (u: User) => u.planets.some(p => p.buildings.find(b => b.id === 'mine_risitasium' && b.level >= 1))
    },
    {
        id: 'q_power',
        title: 'Lumière Divine',
        description: 'Construire une Centrale Solaire niveau 1 pour alimenter vos mines.',
        reward: { risitasium: 300 },
        condition: (u: User) => u.planets.some(p => p.buildings.find(b => b.id === 'centrale_solaire' && b.level >= 1))
    },
    {
        id: 'q_lab',
        title: 'Science infuse',
        description: 'Construire un Laboratoire de Recherche niveau 1.',
        reward: { sel: 100 },
        condition: (u: User) => u.planets.some(p => p.buildings.find(b => b.id === 'laboratoire_recherche' && b.level >= 1))
    },
    {
        id: 'q_fleet',
        title: 'Armada',
        description: 'Posséder au moins 1 Chasseur Léger.',
        reward: { redpills: 10 },
        condition: (u: User) => u.planets.some(p => p.fleet.find(s => s.id === 'chasseur_leger' && s.count >= 1))
    }
];

export const OFFICER_DB: Officer[] = [
  {
    id: 'off_celestin',
    name: 'Ingénieur Célestin',
    description: 'Optimise la production d\'énergie en pédalant plus vite.',
    cost: 100,
    bonus: '+10% Production Énergie',
    active: false,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'off_modo',
    name: 'Modérateur Corrompu',
    description: 'Ferme les yeux sur vos activités illicites.',
    cost: 250,
    bonus: '+2 Slots de Flotte',
    active: false,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'off_stalker',
    name: 'Commandant Stalker',
    description: 'Améliore la vitesse des vaisseaux lors des raids.',
    cost: 500,
    bonus: '+10% Vitesse Flotte',
    active: false,
    image: 'https://images.unsplash.com/photo-1614726365723-49faaa559036?q=80&w=500&auto=format&fit=crop'
  }
];

// NEW: Talents
export const TALENT_TREE: Talent[] = [
    { id: 't_raid_speed', name: 'Postcombustion', description: 'Augmente la vitesse de la flotte.', branch: 'raider', tier: 1, maxLevel: 5, currentLevel: 0, effect: (v) => `+${v*2}% Vitesse` },
    { id: 't_mine_boost', name: 'Optimisation', description: 'Augmente la production des mines.', branch: 'miner', tier: 1, maxLevel: 5, currentLevel: 0, effect: (v) => `+${v*2}% Production` },
    { id: 't_spy_tech', name: 'Cryptographie', description: 'Améliore la technologie d\'espionnage.', branch: 'strategist', tier: 1, maxLevel: 3, currentLevel: 0, effect: (v) => `+${v} Niv Espionnage` },
];

// NEW: Artifacts
export const ARTIFACT_DB: Artifact[] = [
    { id: 'art_warp_core', name: 'Noyau Instable', description: 'Un coeur de réacteur antique.', rarity: 'legendary', effectType: 'speed', quantity: 0, image: 'https://images.unsplash.com/photo-1618557219685-b98c3b3c473e?q=80&w=100' },
    { id: 'art_ancient_map', name: 'Carte Stellaire', description: 'Coordonnées de secteurs riches.', rarity: 'rare', effectType: 'resource', quantity: 0, image: 'https://images.unsplash.com/photo-1465101162946-4377e57745c3?q=80&w=100' },
];

export const DEFENSE_DB: Defense[] = [
  {
    id: 'lanceur_pls',
    name: 'Lanceur de PLS',
    description: 'Tourelle de base. Met l\'ennemi en Position Latérale de Sécurité.',
    count: 0,
    baseCost: { risitasium: 2000, stickers: 0, sel: 0 },
    costFactor: 1,
    basePoints: 2,
    stats: { attack: 80, defense: 20, hull: 200, capacity: 0 },
    reqs: { 'chantier_spatial': 1 },
    image: 'https://images.unsplash.com/photo-1589987820063-8e100259163e?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'laser_gneugneu',
    name: 'Laser "Gneu Gneu"',
    description: 'Émet une fréquence agaçante qui perturbe les boucliers.',
    count: 0,
    baseCost: { risitasium: 1500, stickers: 500, sel: 0 },
    costFactor: 1,
    basePoints: 4,
    stats: { attack: 100, defense: 25, hull: 200, capacity: 0 },
    reqs: { 'chantier_spatial': 2, 'tech_laser': 3 },
    image: 'https://images.unsplash.com/photo-1491591462767-3b91b2a19487?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'canon_pave',
    name: 'Canon à Pavé César',
    description: 'Projette des blocs de texte illisibles à haute vélocité.',
    count: 0,
    baseCost: { risitasium: 6000, stickers: 2000, sel: 0 },
    costFactor: 1,
    basePoints: 10,
    stats: { attack: 250, defense: 100, hull: 800, capacity: 0 },
    reqs: { 'chantier_spatial': 6, 'tech_energie': 6, 'tech_armure': 3 },
    image: 'https://images.unsplash.com/photo-1590422964522-83569727402c?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'bouclier_safe_space',
    name: 'Dôme Safe Space',
    description: 'Protège la colonie des agressions visuelles.',
    count: 0,
    baseCost: { risitasium: 10000, stickers: 10000, sel: 0 },
    costFactor: 1,
    basePoints: 25,
    stats: { attack: 1, defense: 2000, hull: 2000, capacity: 0 },
    reqs: { 'chantier_spatial': 1, 'tech_bouclier': 2 },
    image: 'https://images.unsplash.com/photo-1468273513361-9c6a17b87827?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'canon_plasma',
    name: 'Projecteur de Malaise',
    description: 'L\'arme ultime. Crée un malaise si intense que les vaisseaux explosent.',
    count: 0,
    baseCost: { risitasium: 50000, stickers: 50000, sel: 30000 },
    costFactor: 1,
    basePoints: 150,
    stats: { attack: 3000, defense: 3000, hull: 10000, capacity: 0 },
    reqs: { 'chantier_spatial': 8, 'tech_plasma': 7 },
    image: 'https://images.unsplash.com/photo-1628126235206-5260b9ea6441?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'missile_interception',
    name: 'Missile d\'Interception',
    description: 'Détruit les Missiles Interplanétaires ennemis en vol.',
    count: 0,
    baseCost: { risitasium: 8000, stickers: 0, sel: 2000 },
    costFactor: 1,
    basePoints: 10,
    stats: { attack: 1, defense: 1, hull: 1, capacity: 0 },
    reqs: { 'silo_missiles': 2 },
    image: 'https://images.unsplash.com/photo-1550482645-8c0c45167b0b?q=80&w=500&auto=format&fit=crop'
  },
  {
    id: 'missile_interplanetaire',
    name: 'Missile Interplanétaire',
    description: 'Détruit les défenses adverses à distance.',
    count: 0,
    baseCost: { risitasium: 12500, stickers: 2500, sel: 10000 },
    costFactor: 1,
    basePoints: 25,
    stats: { attack: 12000, defense: 1, hull: 1, capacity: 0 },
    reqs: { 'silo_missiles': 4, 'moteur_impulsion': 1 },
    image: 'https://images.unsplash.com/photo-1609605776950-57577884d565?q=80&w=500&auto=format&fit=crop'
  }
];

export const BUILDING_DB: Building[] = [
  {
    id: 'mine_risitasium',
    name: 'Mine de Risitium',
    description: 'Extraction du minerai brut.',
    longDescription: 'Le Risitium est un métal extrêmement dense trouvé dans les profondeurs de la croûte terrestre des Topics. C\'est l\'élément fondateur de toute civilisation khey. Cette mine creuse inlassablement le sol pour remonter ce précieux matériau.',
    level: 0,
    baseCost: { risitasium: 60, stickers: 15, sel: 0 },
    costFactor: 1.5,
    basePoints: 1,
    baseTime: 10, 
    timeFactor: 1.6, 
    production: { type: 'risitasium', base: 30, factor: 1.1 },
    energyType: 'consumer',
    consumption: { type: 'karma', base: 10, factor: 1.1 },
    image: 'https://images.unsplash.com/photo-1516937941344-00b4ec0c4663?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'extracteur_stickers',
    name: 'Extracteur de Stickers',
    description: 'Cristallisation de données mémétiques.',
    longDescription: 'Les Stickers ne sont pas de simples images, ce sont des cristaux de données pures. L\'extracteur filtre le bruit ambiant du réseau pour cristalliser ces mèmes en matière utilisable.',
    level: 0,
    baseCost: { risitasium: 48, stickers: 24, sel: 0 },
    costFactor: 1.6,
    basePoints: 1,
    baseTime: 10,
    timeFactor: 1.6,
    production: { type: 'stickers', base: 20, factor: 1.1 },
    energyType: 'consumer',
    consumption: { type: 'karma', base: 10, factor: 1.1 },
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'raffineur_sel',
    name: 'Raffineur de Sel',
    description: 'Synthèse d\'isotopes lourds toxiques.',
    longDescription: 'Le Sel est un isotope lourd récolté dans l\'atmosphère toxique des sous-forums. Il sert de carburant haute performance pour les moteurs hyperespace et de réactif pour les recherches nucléaires.',
    level: 0,
    baseCost: { risitasium: 225, stickers: 75, sel: 0 },
    costFactor: 1.5,
    basePoints: 3,
    baseTime: 15,
    timeFactor: 1.6,
    production: { type: 'sel', base: 8, factor: 1.1 }, 
    energyType: 'consumer',
    consumption: { type: 'karma', base: 20, factor: 1.1 },
    image: 'https://images.unsplash.com/photo-1518337231011-7b24300e84b6?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'centrale_solaire',
    name: 'Centrale Solaire',
    description: 'Conversion photonique basique.',
    longDescription: 'Des panneaux photovoltaïques géants qui convertissent la lumière de l\'étoile locale en Karma positif. C\'est la source d\'énergie la plus basique et la plus fiable.',
    level: 0,
    baseCost: { risitasium: 75, stickers: 30, sel: 0 },
    costFactor: 1.5,
    basePoints: 2,
    baseTime: 10,
    timeFactor: 1.5,
    production: { type: 'karma', base: 20, factor: 1.1 },
    energyType: 'producer',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'centrale_fusion',
    name: 'Réacteur à Fusion',
    description: 'Générateur haute énergie au Sel.',
    longDescription: 'En fusionnant des atomes de Sel sous haute pression, cette centrale génère une quantité phénoménale de Karma. Solution ultime pour l\'industrie lourde.',
    level: 0,
    baseCost: { risitasium: 900, stickers: 360, sel: 180 },
    costFactor: 1.8,
    basePoints: 15,
    baseTime: 200,
    timeFactor: 1.8,
    production: { type: 'karma', base: 50, factor: 1.1 },
    energyType: 'producer',
    consumption: { type: 'sel', base: 5, factor: 1.1 },
    image: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'hangar_risitasium',
    name: 'Hangar de Risitium',
    description: 'Augmente la capacité de stockage du Risitium.',
    longDescription: 'Un immense entrepôt blindé permettant de stocker le minerai brut à l\'abri des intempéries et des pillards.',
    level: 0,
    baseCost: { risitasium: 1000, stickers: 0, sel: 0 },
    costFactor: 2,
    basePoints: 5,
    baseTime: 200,
    timeFactor: 1.6,
    energyType: 'consumer',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'hangar_stickers',
    name: 'Hangar de Stickers',
    description: 'Augmente la capacité de stockage des Stickers.',
    longDescription: 'Un serveur de données ultra-sécurisé et refroidi pour stocker des pétaoctets de mèmes cristallisés.',
    level: 0,
    baseCost: { risitasium: 1000, stickers: 500, sel: 0 },
    costFactor: 2,
    basePoints: 5,
    baseTime: 200,
    timeFactor: 1.6,
    energyType: 'consumer',
    image: 'https://images.unsplash.com/photo-1558494949-ef526b0042a0?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'reservoir_sel',
    name: 'Réservoir de Sel',
    description: 'Augmente la capacité de stockage du Sel.',
    longDescription: 'Cuves pressurisées et blindées au plomb pour contenir les isotopes toxiques du Sel.',
    level: 0,
    baseCost: { risitasium: 1000, stickers: 1000, sel: 0 },
    costFactor: 2,
    basePoints: 5,
    baseTime: 200,
    timeFactor: 1.6,
    energyType: 'consumer',
    image: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'usine_golems',
    name: 'Usine de Golems',
    description: 'Réduit le temps de construction des bâtiments.',
    longDescription: 'Une chaîne de montage automatisée qui produit des ouvriers incatigables. Chaque niveau optimise la logistique et réduit drastiquement les temps de construction.',
    level: 0,
    baseCost: { risitasium: 400, stickers: 120, sel: 200 },
    costFactor: 2,
    basePoints: 10,
    baseTime: 150, 
    timeFactor: 1.65, 
    energyType: 'consumer',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'laboratoire_recherche',
    name: 'Labo de Recherche',
    description: 'Centre de développement technologique.',
    longDescription: 'Le centre névralgique de l\'intelligence de votre empire. Ici, les savants étudient les mystères du Risitium et du Sel pour développer de nouveaux moteurs.',
    level: 0,
    baseCost: { risitasium: 1000, stickers: 2000, sel: 1000 }, 
    costFactor: 2,
    basePoints: 10,
    baseTime: 150, 
    timeFactor: 1.5, 
    energyType: 'consumer',
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'chantier_spatial',
    name: 'Chantier Spatial',
    description: 'Dock d\'assemblage de flotte.',
    longDescription: 'Un immense dock orbital capable d\'assembler des coques en alliage de Risitium. Nécessaire pour construire aussi bien des transporteurs civils que des croiseurs de bataille.',
    level: 0,
    baseCost: { risitasium: 2000, stickers: 1000, sel: 500 },
    costFactor: 2,
    basePoints: 10,
    baseTime: 150, 
    timeFactor: 1.6, 
    energyType: 'consumer',
    reqs: { 'usine_golems': 2 },
    image: 'https://images.unsplash.com/photo-1614728853970-309140b774cf?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'silo_missiles',
    name: 'Silo de Missiles',
    description: 'Stockage pour missiles.',
    longDescription: 'Structure souterraine renforcée permettant le stockage et le lancement de missiles interplanétaires et d\'interception.',
    level: 0,
    baseCost: { risitasium: 20000, stickers: 20000, sel: 1000 },
    costFactor: 2,
    basePoints: 20,
    baseTime: 500,
    timeFactor: 1.8,
    energyType: 'consumer',
    reqs: { 'chantier_spatial': 1 },
    image: 'https://images.unsplash.com/photo-1517411032315-54ef2cb00966?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'phalange_capteur',
    name: 'Phalange de Capteur',
    description: 'Scanner longue portée (Lune).',
    longDescription: 'Réseau de capteurs haute sensibilité capable de détecter les mouvements de flotte sur les planètes voisines.',
    level: 0,
    baseCost: { risitasium: 20000, stickers: 40000, sel: 20000 },
    costFactor: 2,
    basePoints: 50,
    baseTime: 500,
    timeFactor: 1.8,
    energyType: 'consumer',
    consumption: { type: 'karma', base: 1000, factor: 1.5 }, 
    reqs: { 'base_lunaire': 1 }, 
    image: 'https://images.unsplash.com/photo-1614728263952-84ea2563bc10?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
    isMoonOnly: true
  },
  {
    id: 'terraformeur',
    name: 'Terraformeur',
    description: 'Augmente le nombre de cases.',
    longDescription: 'Des nanomachines remodèlent la surface de la planète pour la rendre exploitable. Chaque niveau ajoute 5 cases mais consomme énormément d\'énergie.',
    level: 0,
    baseCost: { risitasium: 0, stickers: 50000, sel: 100000 },
    costFactor: 2,
    basePoints: 200,
    baseTime: 1000,
    timeFactor: 2,
    energyType: 'consumer',
    consumption: { type: 'karma', base: 1000, factor: 2 }, 
    reqs: { 'usine_golems': 10, 'tech_energie': 12 }, 
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
  },
  {
    id: 'base_lunaire',
    name: 'Base Lunaire',
    description: 'Infrastructure pour Lune.',
    longDescription: 'Permet de construire des bâtiments sur la lune. Chaque niveau ajoute 3 cases.',
    level: 0,
    baseCost: { risitasium: 20000, stickers: 40000, sel: 20000 },
    costFactor: 2,
    basePoints: 100,
    baseTime: 24 * 3600, // 1 Day base
    timeFactor: 1.5,
    reqs: {}, 
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
    isMoonOnly: true
  },
  {
    id: 'porte_saut',
    name: 'Porte de Saut',
    description: 'Transport instantané.',
    longDescription: 'Permet d\'envoyer instantanément une flotte vers une autre lune possédant une porte de saut. Coût nul en Sel mais recharge longue.',
    level: 0,
    baseCost: { risitasium: 2000000, stickers: 4000000, sel: 2000000 },
    costFactor: 2,
    basePoints: 5000,
    baseTime: 3 * 24 * 3600, 
    timeFactor: 1.2,
    reqs: { 'base_lunaire': 1, 'tech_hyperespace': 7 }, 
    image: 'https://images.unsplash.com/photo-1506318137071-a8bcbf6755dd?q=80&w=500&auto=format&fit=crop',
    percentage: 100,
    isMoonOnly: true
  }
];

export const RESEARCH_DB: Research[] = [
  {
    id: 'tech_energie',
    name: 'Théorie du Karma',
    description: 'Compréhension des flux énergétiques.',
    level: 0,
    baseCost: { risitasium: 0, stickers: 800, sel: 400 },
    costFactor: 2,
    basePoints: 5,
    baseTime: 100,
    timeFactor: 1.5,
    reqs: { 'laboratoire_recherche': 1 },
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_laser',
    name: 'Rayon DDB',
    description: 'Concentration de signalements à haute intensité.',
    level: 0,
    baseCost: { risitasium: 200, stickers: 100, sel: 0 },
    costFactor: 2,
    basePoints: 3,
    baseTime: 100,
    timeFactor: 1.5,
    reqs: { 'laboratoire_recherche': 2, 'tech_energie': 1 },
    image: 'https://images.unsplash.com/photo-1574360778004-945d8b2d4957?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_ions',
    name: 'Canon à Shitpost',
    description: 'Bombardement ionique de masse.',
    level: 0,
    baseCost: { risitasium: 1000, stickers: 300, sel: 100 },
    costFactor: 2,
    basePoints: 10,
    baseTime: 300,
    timeFactor: 1.6,
    reqs: { 'laboratoire_recherche': 4, 'tech_laser': 5, 'tech_energie': 4 },
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_hyperespace',
    name: 'Faille 410',
    description: 'Manipulation de l\'espace-temps pour disparaître.',
    level: 0,
    baseCost: { risitasium: 0, stickers: 4000, sel: 2000 },
    costFactor: 2,
    basePoints: 30,
    baseTime: 600,
    timeFactor: 1.7,
    reqs: { 'laboratoire_recherche': 7, 'tech_energie': 5, 'tech_bouclier': 5 },
    image: 'https://images.unsplash.com/photo-1506318137071-a8bcbf6755dd?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_plasma',
    name: 'Technologie Plasma',
    description: 'L\'état ultime de la matière toxique.',
    level: 0,
    baseCost: { risitasium: 2000, stickers: 4000, sel: 1000 },
    costFactor: 2,
    basePoints: 20,
    baseTime: 500,
    timeFactor: 1.7,
    reqs: { 'laboratoire_recherche': 4, 'tech_energie': 8, 'tech_laser': 10 },
    image: 'https://images.unsplash.com/photo-1533613220915-609f661a6fe1?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'moteur_combustion',
    name: 'Moteur Diesel',
    description: 'Propulsion classique polluante.',
    level: 0,
    baseCost: { risitasium: 400, stickers: 0, sel: 600 },
    costFactor: 2,
    basePoints: 5,
    baseTime: 200,
    timeFactor: 1.5,
    reqs: { 'laboratoire_recherche': 1, 'tech_energie': 1 },
    image: 'https://images.unsplash.com/photo-1580637250482-5c8e3100693a?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'moteur_impulsion',
    name: 'Propulsion Hype',
    description: 'Moteur alimenté par la tendance.',
    level: 0,
    baseCost: { risitasium: 2000, stickers: 4000, sel: 600 },
    costFactor: 2,
    basePoints: 15,
    baseTime: 400,
    timeFactor: 1.6,
    reqs: { 'laboratoire_recherche': 2, 'tech_energie': 1 },
    image: 'https://images.unsplash.com/photo-1542475510-99e53a1a387a?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'moteur_hyperspace',
    name: 'Propulsion Spatio-Temporelle',
    description: 'Voyager plus vite que la modération.',
    level: 0,
    baseCost: { risitasium: 10000, stickers: 20000, sel: 6000 },
    costFactor: 2,
    basePoints: 50,
    baseTime: 800,
    timeFactor: 1.7,
    reqs: { 'laboratoire_recherche': 7, 'tech_hyperespace': 3 },
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'espionnage',
    name: 'Algorithme de Stalking',
    description: 'Améliore la collecte d\'informations.',
    level: 0,
    baseCost: { risitasium: 200, stickers: 1000, sel: 200 },
    costFactor: 2,
    basePoints: 4,
    baseTime: 150,
    timeFactor: 1.5,
    reqs: { 'laboratoire_recherche': 3 },
    image: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'ordinateur',
    name: 'I.A. Célestin',
    description: 'Gère plus de flottes simultanément.',
    level: 0,
    baseCost: { risitasium: 0, stickers: 400, sel: 600 },
    costFactor: 2,
    basePoints: 6,
    baseTime: 200,
    timeFactor: 1.5,
    reqs: { 'laboratoire_recherche': 1 },
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_armure',
    name: 'Blindage Anti-Ban',
    description: 'Renforce la structure des vaisseaux.',
    level: 0,
    baseCost: { risitasium: 1000, stickers: 0, sel: 0 },
    costFactor: 2,
    basePoints: 5,
    baseTime: 300,
    timeFactor: 1.5,
    reqs: { 'laboratoire_recherche': 2 },
    image: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'tech_bouclier',
    name: 'Bouclier "Miroir Magique"',
    description: 'Renvoie les attaques à l\'envoyeur.',
    level: 0,
    baseCost: { risitasium: 200, stickers: 600, sel: 0 },
    costFactor: 2,
    basePoints: 5,
    baseTime: 300,
    timeFactor: 1.5,
    reqs: { 'laboratoire_recherche': 6, 'tech_energie': 3 },
    image: 'https://images.unsplash.com/photo-1517480447814-2396e9877114?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'astrophysique',
    name: 'Astrophysique',
    description: 'Permet de découvrir et coloniser de nouveaux mondes.',
    level: 0,
    baseCost: { risitasium: 4000, stickers: 8000, sel: 4000 },
    costFactor: 2,
    basePoints: 40,
    baseTime: 600,
    timeFactor: 1.7,
    reqs: { 'laboratoire_recherche': 3, 'espionnage': 4, 'moteur_impulsion': 3 },
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'graviton',
    name: 'Technologie Graviton',
    description: 'Nécessaire pour l\'Étoile Noire. Requiert une énergie colossale.',
    level: 0,
    baseCost: { risitasium: 0, stickers: 0, sel: 0 }, // Fake cost, needs energy check in logic
    costFactor: 3,
    basePoints: 1000,
    baseTime: 1, // Instant if you have energy
    timeFactor: 1,
    reqs: { 'laboratoire_recherche': 12 },
    image: 'https://images.unsplash.com/photo-1505322022379-7c3353ee6291?q=80&w=500&auto=format&fit=crop',
  }
];

export const SHIP_DB: Ship[] = [
  {
    id: 'chasseur_leger',
    name: 'Chasseur Léger',
    description: 'Vaisseau de combat agile.',
    longDescription: 'Le premier vaisseau de combat disponible. Rapide et peu coûteux, il sert souvent de chair à canon.',
    count: 0,
    baseCost: { risitasium: 3000, stickers: 1000, sel: 0 },
    costFactor: 1,
    basePoints: 4,
    stats: { attack: 50, defense: 10, hull: 400, capacity: 50, rapidFire: {} },
    reqs: { 'chantier_spatial': 1, 'moteur_combustion': 1 },
    image: 'https://images.unsplash.com/photo-1517480447814-2396e9877114?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'chasseur_lourd',
    name: 'Chasseur Lourd',
    description: 'Version blindée du chasseur.',
    longDescription: 'Mieux armé et mieux protégé que le léger, il possède un blindage renforcé.',
    count: 0,
    baseCost: { risitasium: 6000, stickers: 4000, sel: 0 },
    costFactor: 1,
    basePoints: 10,
    stats: { attack: 150, defense: 25, hull: 1000, capacity: 100, rapidFire: { 'petit_transporteur': 3 } },
    reqs: { 'chantier_spatial': 3, 'tech_armure': 2, 'moteur_impulsion': 2 },
    image: 'https://images.unsplash.com/photo-1628126235206-5260b9ea6441?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'croiseur',
    name: 'Croiseur',
    description: 'Vaisseau rapide et polyvalent.',
    longDescription: 'La terreur des chasseurs légers. Sa cadence de tir élevée en fait une arme redoutable.',
    count: 0,
    baseCost: { risitasium: 20000, stickers: 7000, sel: 2000 },
    costFactor: 1,
    basePoints: 29,
    stats: { attack: 400, defense: 50, hull: 2700, capacity: 800, rapidFire: { 'chasseur_leger': 6, 'sonde': 5, 'satellite_solaire': 5 } },
    reqs: { 'chantier_spatial': 5, 'moteur_impulsion': 4, 'tech_ions': 2 },
    image: 'https://images.unsplash.com/photo-1605218427306-635ba243971c?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'vaisseau_bataille',
    name: 'Vaisseau de Bataille',
    description: 'L\'épine dorsale de la flotte.',
    longDescription: 'Lourdement armé et blindé, il est conçu pour détruire les vaisseaux capitaux ennemis.',
    count: 0,
    baseCost: { risitasium: 45000, stickers: 15000, sel: 0 },
    costFactor: 1,
    basePoints: 60,
    stats: { attack: 1000, defense: 200, hull: 6000, capacity: 1500, rapidFire: {} },
    reqs: { 'chantier_spatial': 7, 'moteur_hyperspace': 4 },
    image: 'https://images.unsplash.com/photo-1542475510-99e53a1a387a?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'destructeur',
    name: 'Destructeur',
    description: 'Chasseur de croiseurs.',
    longDescription: 'Un vaisseau immense doté de multiples tourelles, spécialisé dans l\'annihilation des flottes moyennes.',
    count: 0,
    baseCost: { risitasium: 60000, stickers: 50000, sel: 15000 },
    costFactor: 1,
    basePoints: 125,
    stats: { attack: 2000, defense: 500, hull: 11000, capacity: 2000, rapidFire: { 'croiseur': 2, 'laser_gneugneu': 5, 'satellite_solaire': 5 } },
    reqs: { 'chantier_spatial': 9, 'moteur_hyperspace': 6, 'tech_hyperspace': 5 },
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'etoile_noire',
    name: 'Étoile Noire',
    description: 'L\'arme ultime.',
    longDescription: 'Une station spatiale mobile de la taille d\'une lune. Sa puissance de feu est inégalée.',
    count: 0,
    baseCost: { risitasium: 5000000, stickers: 4000000, sel: 1000000 },
    costFactor: 1,
    basePoints: 10000,
    stats: { attack: 200000, defense: 50000, hull: 9000000, capacity: 1000000, rapidFire: { 'croiseur': 10, 'vaisseau_bataille': 5, 'destructeur': 2, 'satellite_solaire': 100 } },
    reqs: { 'chantier_spatial': 12, 'moteur_hyperspace': 7, 'graviton': 1 },
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'petit_transporteur',
    name: 'Petit Transporteur',
    description: 'Transport rapide de ressources.',
    longDescription: 'Essentiel pour le commerce et le pillage rapide.',
    count: 0,
    baseCost: { risitasium: 2000, stickers: 2000, sel: 0 },
    costFactor: 1,
    basePoints: 4,
    stats: { attack: 5, defense: 10, hull: 400, capacity: 5000, rapidFire: {} },
    reqs: { 'chantier_spatial': 2, 'moteur_combustion': 2 },
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'grand_transporteur',
    name: 'Grand Transporteur',
    description: 'Fret lourd.',
    longDescription: 'Grande capacité de soute, mais lent et peu armé.',
    count: 0,
    baseCost: { risitasium: 6000, stickers: 6000, sel: 0 },
    costFactor: 1,
    basePoints: 12,
    stats: { attack: 5, defense: 25, hull: 1200, capacity: 25000, rapidFire: {} },
    reqs: { 'chantier_spatial': 4, 'moteur_combustion': 6 },
    image: 'https://images.unsplash.com/photo-1545156526-9052c99a6f7b?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'colonisateur',
    name: 'Vaisseau de Colonisation',
    description: 'Permet de fonder une nouvelle colonie.',
    longDescription: 'Transporte le matériel et les colons nécessaires pour établir une base sur une planète vierge.',
    count: 0,
    baseCost: { risitasium: 10000, stickers: 20000, sel: 10000 },
    costFactor: 1,
    basePoints: 40,
    stats: { attack: 50, defense: 100, hull: 3000, capacity: 7500, rapidFire: {} },
    reqs: { 'chantier_spatial': 4, 'moteur_impulsion': 3 },
    image: 'https://images.unsplash.com/photo-1454789548728-85d2696cf664?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'recycleur',
    name: 'Recycleur',
    description: 'Récolte les débris spatiaux.',
    longDescription: 'Équipé de boucliers pour naviguer dans les champs de débris et de grappins pour récupérer les matériaux.',
    count: 0,
    baseCost: { risitasium: 10000, stickers: 6000, sel: 2000 },
    costFactor: 1,
    basePoints: 18,
    stats: { attack: 1, defense: 10, hull: 1600, capacity: 20000, rapidFire: {} },
    reqs: { 'chantier_spatial': 4, 'moteur_combustion': 6, 'tech_bouclier': 2 },
    image: 'https://images.unsplash.com/photo-1506318137071-a8bcbf6755dd?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'sonde',
    name: 'Sonde d\'espionnage',
    description: 'Petit drone rapide pour scanner les planètes.',
    longDescription: 'Ne possède quasiment aucune défense, mais est très rapide.',
    count: 0,
    baseCost: { risitasium: 0, stickers: 1000, sel: 0 },
    costFactor: 1,
    basePoints: 1,
    stats: { attack: 0, defense: 0, hull: 100, capacity: 5, rapidFire: {} },
    reqs: { 'chantier_spatial': 3, 'moteur_combustion': 3, 'espionnage': 2 },
    image: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 'satellite_solaire',
    name: 'Satellite Solaire',
    description: 'Produit de l\'énergie en orbite.',
    longDescription: 'Déployés en haute orbite, ces satellites captent directement l\'énergie solaire brute. Indispensable pour l\'énergie d\'appoint ou le Graviton.',
    count: 0,
    baseCost: { risitasium: 0, stickers: 2000, sel: 500 },
    costFactor: 1,
    basePoints: 1,
    stats: { attack: 0, defense: 0, hull: 200, capacity: 0, rapidFire: {} },
    reqs: { 'chantier_spatial': 1 },
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=500&auto=format&fit=crop',
  }
];
